name: Build ghidra-rest-api

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra: [ '11.0.3', '11.1', '11.1.1' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - name: Setup Ghidra
        uses: antoniovazquezblanco/setup-ghidra@021eb688b995b2c3aa4d607dea9cb332ab4eb9c8
        with:
          version: ${{ matrix.ghidra }}
      - name: Build Extension
        run: |
          chmod +x gradlew
          ./gradlew buildExtension
      - name: Upload artifact to workflow
        uses: actions/upload-artifact@v4
        with:
          path: dist/*ghidra-rest-api.zip
          name: ghidra-rest-api-snapshot-for-Ghidra-${{ matrix.ghidra }}
          if-no-files-found: error
      - name: Upload artifact to release
        if: github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ghidra-rest-api ${{ github.ref_name }}
          file: dist/*ghidra-rest-api.zip
          file_glob: true
          body: See [CHANGES](https://github.com/kotcrab/ghidra-rest-api/blob/master/CHANGES.md) file before updating.
          tag: ${{ github.ref }}
